//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgOpenGPS.Culture {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class gStr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal gStr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgOpenGPS.Culture.gStr", typeof(gStr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YouTube Tutorials.
        /// </summary>
        public static string gs_YoutubeTutorials {
            get {
                return ResourceManager.GetString("gs.YoutubeTutorials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AB Curve.
        /// </summary>
        public static string gsABCurve {
            get {
                return ResourceManager.GetString("gsABCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AB Line.
        /// </summary>
        public static string gsABline {
            get {
                return ResourceManager.GetString("gsABline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        public static string gsAbout {
            get {
                return ResourceManager.GetString("gsAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About AgOpenGPS.
        /// </summary>
        public static string gsAboutAOG {
            get {
                return ResourceManager.GetString("gsAboutAOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Terms and Conditions.
        /// </summary>
        public static string gsAccepTerms {
            get {
                return ResourceManager.GetString("gsAccepTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn steering wheel to LEFT roughly the same degrees as right.
        ///While driving in a steady circle, Press Rec and wait..
        /// </summary>
        public static string gsAckermannNote {
            get {
                return ResourceManager.GetString("gsAckermannNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ackermann Value.
        /// </summary>
        public static string gsAckermannValue {
            get {
                return ResourceManager.GetString("gsAckermannValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Has Been Cancelled.
        /// </summary>
        public static string gsActionHasBeenCancelled {
            get {
                return ResourceManager.GetString("gsActionHasBeenCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual.
        /// </summary>
        public static string gsActual {
            get {
                return ResourceManager.GetString("gsActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A/D Converter.
        /// </summary>
        public static string gsADConverter {
            get {
                return ResourceManager.GetString("gsADConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A/D Converter Connection?.
        /// </summary>
        public static string gsADConverterConnection {
            get {
                return ResourceManager.GetString("gsADConverterConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agressiveness.
        /// </summary>
        public static string gsAgressiveness {
            get {
                return ResourceManager.GetString("gsAgressiveness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antenna.
        /// </summary>
        public static string gsAntenna {
            get {
                return ResourceManager.GetString("gsAntenna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antenna 
        ///Height.
        /// </summary>
        public static string gsAntennaHeight {
            get {
                return ResourceManager.GetString("gsAntennaHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antenna Offset.
        /// </summary>
        public static string gsAntennaOffset {
            get {
                return ResourceManager.GetString("gsAntennaOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antenna Position.
        /// </summary>
        public static string gsAntennaPosition {
            get {
                return ResourceManager.GetString("gsAntennaPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string gsArea {
            get {
                return ResourceManager.GetString("gsArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure ?.
        /// </summary>
        public static string gsAreYouSure {
            get {
                return ResourceManager.GetString("gsAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Canceling Feature.
        /// </summary>
        public static string gsAutomaticCancel {
            get {
                return ResourceManager.GetString("gsAutomaticCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Steer.
        /// </summary>
        public static string gsAutoSteer {
            get {
                return ResourceManager.GetString("gsAutoSteer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Steer Configuration.
        /// </summary>
        public static string gsAutoSteerConfiguration {
            get {
                return ResourceManager.GetString("gsAutoSteerConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoSteer Port.
        /// </summary>
        public static string gsAutoSteerPort {
            get {
                return ResourceManager.GetString("gsAutoSteerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Based on Field:.
        /// </summary>
        public static string gsBasedOnField {
            get {
                return ResourceManager.GetString("gsBasedOnField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Begin* Calibration.
        /// </summary>
        public static string gsBeginCalibration {
            get {
                return ResourceManager.GetString("gsBeginCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boundary.
        /// </summary>
        public static string gsBoundary {
            get {
                return ResourceManager.GetString("gsBoundary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boundary Lines File Corrupt.
        /// </summary>
        public static string gsBoundaryLineFilesAreCorrupt {
            get {
                return ResourceManager.GetString("gsBoundaryLineFilesAreCorrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boundary Contour.
        /// </summary>
        public static string gsBoundaryMenu {
            get {
                return ResourceManager.GetString("gsBoundaryMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boundary Tool.
        /// </summary>
        public static string gsBoundaryTool {
            get {
                return ResourceManager.GetString("gsBoundaryTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to But Field Is Loaded.
        /// </summary>
        public static string gsButFieldIsLoaded {
            get {
                return ResourceManager.GetString("gsButFieldIsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button.
        /// </summary>
        public static string gsButton {
            get {
                return ResourceManager.GetString("gsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centimeter.
        /// </summary>
        public static string gsCentimeters {
            get {
                return ResourceManager.GetString("gsCentimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        public static string gsCharts {
            get {
                return ResourceManager.GetString("gsCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        public static string gsCheckForUpdates {
            get {
                return ResourceManager.GetString("gsCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a different field.
        /// </summary>
        public static string gsChooseADifferentField {
            get {
                return ResourceManager.GetString("gsChooseADifferentField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a different name.
        /// </summary>
        public static string gsChooseADifferentName {
            get {
                return ResourceManager.GetString("gsChooseADifferentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose or Build a Different one.
        /// </summary>
        public static string gsChooseBuildDifferentone {
            get {
                return ResourceManager.GetString("gsChooseBuildDifferentone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string gsClose {
            get {
                return ResourceManager.GetString("gsClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close All Windows First.
        /// </summary>
        public static string gsCloseAllWindowsFirst {
            get {
                return ResourceManager.GetString("gsCloseAllWindowsFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Field First.
        /// </summary>
        public static string gsCloseFieldFirst {
            get {
                return ResourceManager.GetString("gsCloseFieldFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        public static string gsColors {
            get {
                return ResourceManager.GetString("gsColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completely Delete Boundary.
        /// </summary>
        public static string gsCompletelyDeleteBoundary {
            get {
                return ResourceManager.GetString("gsCompletelyDeleteBoundary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string gsConfiguration {
            get {
                return ResourceManager.GetString("gsConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contour File Corrupt.
        /// </summary>
        public static string gsContourFileIsCorrupt {
            get {
                return ResourceManager.GetString("gsContourFileIsCorrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contour On.
        /// </summary>
        public static string gsContourOn {
            get {
                return ResourceManager.GetString("gsContourOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrected Easting.
        /// </summary>
        public static string gsCorrectedEasting {
            get {
                return ResourceManager.GetString("gsCorrectedEasting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correction Distance.
        /// </summary>
        public static string gsCorrectionDistance {
            get {
                return ResourceManager.GetString("gsCorrectionDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Valid Path.
        /// </summary>
        public static string gsCouldntGenerateValidPath {
            get {
                return ResourceManager.GetString("gsCouldntGenerateValidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counts per Degree.
        /// </summary>
        public static string gsCountsPerDegree {
            get {
                return ResourceManager.GetString("gsCountsPerDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn steering wheel to RIGHT about 20 degrees.
        ///While driving in a steady circle, Press Rec and wait..
        /// </summary>
        public static string gsCPDNote {
            get {
                return ResourceManager.GetString("gsCPDNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string gsCreate {
            get {
                return ResourceManager.GetString("gsCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create A Boundary First.
        /// </summary>
        public static string gsCreateABoundaryFirst {
            get {
                return ResourceManager.GetString("gsCreateABoundaryFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Field.
        /// </summary>
        public static string gsCreateNewField {
            get {
                return ResourceManager.GetString("gsCreateNewField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string gsCurrent {
            get {
                return ResourceManager.GetString("gsCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Heading.
        /// </summary>
        public static string gsCurrentHeading {
            get {
                return ResourceManager.GetString("gsCurrentHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Turn Sensor.
        /// </summary>
        public static string gsCurrentTurnSensor {
            get {
                return ResourceManager.GetString("gsCurrentTurnSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curve Line File Corrupt.
        /// </summary>
        public static string gsCurveLineFileIsCorrupt {
            get {
                return ResourceManager.GetString("gsCurveLineFileIsCorrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curve Not ON.
        /// </summary>
        public static string gsCurveNotOn {
            get {
                return ResourceManager.GetString("gsCurveNotOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danfoss Valve.
        /// </summary>
        public static string gsDanfossValve {
            get {
                return ResourceManager.GetString("gsDanfossValve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All Sections And Contours.
        /// </summary>
        public static string gsDeleteAllContoursAndSections {
            get {
                return ResourceManager.GetString("gsDeleteAllContoursAndSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Applied Area.
        /// </summary>
        public static string gsDeleteAppliedArea {
            get {
                return ResourceManager.GetString("gsDeleteAppliedArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action will delete all the boundaries. Do you want to continue?.
        /// </summary>
        public static string gsDeleteBoundaryMapping {
            get {
                return ResourceManager.GetString("gsDeleteBoundaryMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Contour Paths.
        /// </summary>
        public static string gsDeleteContourPaths {
            get {
                return ResourceManager.GetString("gsDeleteContourPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete For Sure?.
        /// </summary>
        public static string gsDeleteForSure {
            get {
                return ResourceManager.GetString("gsDeleteForSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diameter.
        /// </summary>
        public static string gsDiameter {
            get {
                return ResourceManager.GetString("gsDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differential.
        /// </summary>
        public static string gsDifferential {
            get {
                return ResourceManager.GetString("gsDifferential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories.
        /// </summary>
        public static string gsDirectories {
            get {
                return ResourceManager.GetString("gsDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Exists.
        /// </summary>
        public static string gsDirectoryExists {
            get {
                return ResourceManager.GetString("gsDirectoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disagree.
        /// </summary>
        public static string gsDisagree {
            get {
                return ResourceManager.GetString("gsDisagree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discussions at.....
        /// </summary>
        public static string gsDiscussion {
            get {
                return ResourceManager.GetString("gsDiscussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string gsDistance {
            get {
                return ResourceManager.GetString("gsDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have a Danfoss Valve?.
        /// </summary>
        public static string gsDoYouHaveDanfoss {
            get {
                return ResourceManager.GetString("gsDoYouHaveDanfoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive In.
        /// </summary>
        public static string gsDriveIn {
            get {
                return ResourceManager.GetString("gsDriveIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Control Relay.
        /// </summary>
        public static string gsDriverControlRelay {
            get {
                return ResourceManager.GetString("gsDriverControlRelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive Steady.
        /// </summary>
        public static string gsDriveSteady {
            get {
                return ResourceManager.GetString("gsDriveSteady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive Thru.
        /// </summary>
        public static string gsDriveThru {
            get {
                return ResourceManager.GetString("gsDriveThru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving.
        /// </summary>
        public static string gsDriving {
            get {
                return ResourceManager.GetString("gsDriving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East.
        /// </summary>
        public static string gsEast {
            get {
                return ResourceManager.GetString("gsEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit AB Curve.
        /// </summary>
        public static string gsEditABCurve {
            get {
                return ResourceManager.GetString("gsEditABCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit AB Line.
        /// </summary>
        public static string gsEditABLine {
            get {
                return ResourceManager.GetString("gsEditABLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Field Name.
        /// </summary>
        public static string gsEditFieldName {
            get {
                return ResourceManager.GetString("gsEditFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Terms Form.
        /// </summary>
        public static string gsEnableTerms {
            get {
                return ResourceManager.GetString("gsEnableTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counts.
        /// </summary>
        public static string gsEncoderCounts {
            get {
                return ResourceManager.GetString("gsEncoderCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Coordinates For Simulator.
        /// </summary>
        public static string gsEnterCoordinatesForSimulator {
            get {
                return ResourceManager.GetString("gsEnterCoordinatesForSimulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Field Name.
        /// </summary>
        public static string gsEnterFieldName {
            get {
                return ResourceManager.GetString("gsEnterFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Sim Coords.
        /// </summary>
        public static string gsEnterSimCoords {
            get {
                return ResourceManager.GetString("gsEnterSimCoords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string gsError {
            get {
                return ResourceManager.GetString("gsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading KML.
        /// </summary>
        public static string gsErrorreadingKML {
            get {
                return ResourceManager.GetString("gsErrorreadingKML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Viewer.
        /// </summary>
        public static string gsEventViewer {
            get {
                return ResourceManager.GetString("gsEventViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Guides.
        /// </summary>
        public static string gsExtraGuides {
            get {
                return ResourceManager.GetString("gsExtraGuides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        public static string gsField {
            get {
                return ResourceManager.GetString("gsField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field File is Corrupt.
        /// </summary>
        public static string gsFieldFileIsCorrupt {
            get {
                return ResourceManager.GetString("gsFieldFileIsCorrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Is Open.
        /// </summary>
        public static string gsFieldIsOpen {
            get {
                return ResourceManager.GetString("gsFieldIsOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Not Open.
        /// </summary>
        public static string gsFieldNotOpen {
            get {
                return ResourceManager.GetString("gsFieldNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Error.
        /// </summary>
        public static string gsFileError {
            get {
                return ResourceManager.GetString("gsFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished !.
        /// </summary>
        public static string gsFinished {
            get {
                return ResourceManager.GetString("gsFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag By Lat Lon.
        /// </summary>
        public static string gsFlagByLatLon {
            get {
                return ResourceManager.GetString("gsFlagByLatLon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag File Corrupt.
        /// </summary>
        public static string gsFlagFileIsCorrupt {
            get {
                return ResourceManager.GetString("gsFlagFileIsCorrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Now.
        /// </summary>
        public static string gsForNow {
            get {
                return ResourceManager.GetString("gsForNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Existing.
        /// </summary>
        public static string gsFromExisting {
            get {
                return ResourceManager.GetString("gsFromExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From KML.
        /// </summary>
        public static string gsFromKml {
            get {
                return ResourceManager.GetString("gsFromKml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain Setting.
        /// </summary>
        public static string gsGainSetting {
            get {
                return ResourceManager.GetString("gsGainSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive forward and enable Auto Steer.
        /// </summary>
        public static string gsGainSettingNote1 {
            get {
                return ResourceManager.GetString("gsGainSettingNote1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Proportional for good response. 
        ///Set PWM Maximum to limit turning speed..
        /// </summary>
        public static string gsGainSettingNote2 {
            get {
                return ResourceManager.GetString("gsGainSettingNote2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS Data.
        /// </summary>
        public static string gsGpsData {
            get {
                return ResourceManager.GetString("gsGpsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guidance Steer Angle Limit.
        /// </summary>
        public static string gsGuidanceSteerLimit {
            get {
                return ResourceManager.GetString("gsGuidanceSteerLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn steering to your desired limit for guidance and touch OK -&gt;.
        /// </summary>
        public static string gsGuidanceSteerNote1 {
            get {
                return ResourceManager.GetString("gsGuidanceSteerNote1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or Manually Set Guidance Steer Angle Limit.
        /// </summary>
        public static string gsGuidanceSteerNote2 {
            get {
                return ResourceManager.GetString("gsGuidanceSteerNote2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guidance Stopped.
        /// </summary>
        public static string gsGuidanceStopped {
            get {
                return ResourceManager.GetString("gsGuidanceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading Chart.
        /// </summary>
        public static string gsHeadingChart {
            get {
                return ResourceManager.GetString("gsHeadingChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headland.
        /// </summary>
        public static string gsHeadland {
            get {
                return ResourceManager.GetString("gsHeadland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headland Builder.
        /// </summary>
        public static string gsHeadlandBuilder {
            get {
                return ResourceManager.GetString("gsHeadlandBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create and Edit Headland.
        /// </summary>
        public static string gsHeadlandForm {
            get {
                return ResourceManager.GetString("gsHeadlandForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string gsHelp {
            get {
                return ResourceManager.GetString("gsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highly Recommended.
        /// </summary>
        public static string gsHighlyRecommended {
            get {
                return ResourceManager.GetString("gsHighlyRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Agree to the Terms and Conditions.
        /// </summary>
        public static string gsIAgreeToTerms {
            get {
                return ResourceManager.GetString("gsIAgreeToTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If Wrong Direction Tap Vehicle.
        /// </summary>
        public static string gsIfWrongDirectionTapVehicle {
            get {
                return ResourceManager.GetString("gsIfWrongDirectionTapVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inch.
        /// </summary>
        public static string gsInches {
            get {
                return ResourceManager.GetString("gsInches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner.
        /// </summary>
        public static string gsInner {
            get {
                return ResourceManager.GetString("gsInner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert Direction.
        /// </summary>
        public static string gsInvertDirection {
            get {
                return ResourceManager.GetString("gsInvertDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert Hydraulic Enable Relay?.
        /// </summary>
        public static string gsInvertHydraulic {
            get {
                return ResourceManager.GetString("gsInvertHydraulic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert Relays.
        /// </summary>
        public static string gsInvertRelays {
            get {
                return ResourceManager.GetString("gsInvertRelays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert WAS.
        /// </summary>
        public static string gsInvertWAS {
            get {
                return ResourceManager.GetString("gsInvertWAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert WAS Direction.
        /// </summary>
        public static string gsInvertWASDir {
            get {
                return ResourceManager.GetString("gsInvertWASDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steer Angle must be POSITIVE when turning to the RIGHT.
        ///If not, select the Invert WAS..
        /// </summary>
        public static string gsInvertWASNote {
            get {
                return ResourceManager.GetString("gsInvertWASNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiosk Mode.
        /// </summary>
        public static string gsKioskMode {
            get {
                return ResourceManager.GetString("gsKioskMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kmh.
        /// </summary>
        public static string gsKMH {
            get {
                return ResourceManager.GetString("gsKMH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string gsLanguage {
            get {
                return ResourceManager.GetString("gsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string gsLatitude {
            get {
                return ResourceManager.GetString("gsLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string gsLeft {
            get {
                return ResourceManager.GetString("gsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Defaults.
        /// </summary>
        public static string gsLoadDefault {
            get {
                return ResourceManager.GetString("gsLoadDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Defaults.
        /// </summary>
        public static string gsLoadDefaults {
            get {
                return ResourceManager.GetString("gsLoadDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string gsLongitude {
            get {
                return ResourceManager.GetString("gsLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Port.
        /// </summary>
        public static string gsMachinePort {
            get {
                return ResourceManager.GetString("gsMachinePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Boundary Contours.
        /// </summary>
        public static string gsMakeBoundaryContours {
            get {
                return ResourceManager.GetString("gsMakeBoundaryContours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string gsManual {
            get {
                return ResourceManager.GetString("gsManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meters.
        /// </summary>
        public static string gsMeters {
            get {
                return ResourceManager.GetString("gsMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimun Movement Setting.
        /// </summary>
        public static string gsMinimumMovementSetting {
            get {
                return ResourceManager.GetString("gsMinimumMovementSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive slowly straight forward, Allow system to steer.
        /// </summary>
        public static string gsMinimumMovNote1 {
            get {
                return ResourceManager.GetString("gsMinimumMovNote1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Setpoint with steer buttons. 
        ///
        ///Adjust Minumum Movement as high as possible without steer motor or hydraulics moving steering..
        /// </summary>
        public static string gsMinimumMovNote2 {
            get {
                return ResourceManager.GetString("gsMinimumMovNote2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing ABLInes File.
        /// </summary>
        public static string gsMissingABLinesFile {
            get {
                return ResourceManager.GetString("gsMissingABLinesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Boundary File.
        /// </summary>
        public static string gsMissingBoundaryFile {
            get {
                return ResourceManager.GetString("gsMissingBoundaryFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Contour File.
        /// </summary>
        public static string gsMissingContourFile {
            get {
                return ResourceManager.GetString("gsMissingContourFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Flag File.
        /// </summary>
        public static string gsMissingFlagsFile {
            get {
                return ResourceManager.GetString("gsMissingFlagsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Section File.
        /// </summary>
        public static string gsMissingSectionFile {
            get {
                return ResourceManager.GetString("gsMissingSectionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor Driver Board.
        /// </summary>
        public static string gsMotorDriverBoard {
            get {
                return ResourceManager.GetString("gsMotorDriverBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What Style of Motor Driver?.
        /// </summary>
        public static string gsMotorDriverStyle {
            get {
                return ResourceManager.GetString("gsMotorDriverStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mph.
        /// </summary>
        public static string gsMPH {
            get {
                return ResourceManager.GetString("gsMPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEast.
        /// </summary>
        public static string gsN_East {
            get {
                return ResourceManager.GetString("gsN_East", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NWest.
        /// </summary>
        public static string gsN_West {
            get {
                return ResourceManager.GetString("gsN_West", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string gsNew {
            get {
                return ResourceManager.GetString("gsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ABLine Active.
        /// </summary>
        public static string gsNoABLineActive {
            get {
                return ResourceManager.GetString("gsNoABLineActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Boundary.
        /// </summary>
        public static string gsNoBoundary {
            get {
                return ResourceManager.GetString("gsNoBoundary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Fields Found.
        /// </summary>
        public static string gsNoFieldsFound {
            get {
                return ResourceManager.GetString("gsNoFieldsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Guidance Lines.
        /// </summary>
        public static string gsNoGuidanceLines {
            get {
                return ResourceManager.GetString("gsNoGuidanceLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string gsNone {
            get {
                return ResourceManager.GetString("gsNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None Used.
        /// </summary>
        public static string gsNoneUsed {
            get {
                return ResourceManager.GetString("gsNoneUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North.
        /// </summary>
        public static string gsNorth {
            get {
                return ResourceManager.GetString("gsNorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Settings With IMU.
        /// </summary>
        public static string gsNoSettingsWithIMU {
            get {
                return ResourceManager.GetString("gsNoSettingsWithIMU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing Deleted.
        /// </summary>
        public static string gsNothingDeleted {
            get {
                return ResourceManager.GetString("gsNothingDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off at %.
        /// </summary>
        public static string gsOffatPercent {
            get {
                return ResourceManager.GetString("gsOffatPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        public static string gsOffset {
            get {
                return ResourceManager.GetString("gsOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset Fix.
        /// </summary>
        public static string gsOffsetFix {
            get {
                return ResourceManager.GetString("gsOffsetFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string gsOpen {
            get {
                return ResourceManager.GetString("gsOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outer.
        /// </summary>
        public static string gsOuter {
            get {
                return ResourceManager.GetString("gsOuter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overshoot Reduction.
        /// </summary>
        public static string gsOvershootReduction {
            get {
                return ResourceManager.GetString("gsOvershootReduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kmh drop per fix update (3 works well).
        /// </summary>
        public static string gsPanicStopNote {
            get {
                return ResourceManager.GetString("gsPanicStopNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panic Stop Speed.
        /// </summary>
        public static string gsPanicStopSpeed {
            get {
                return ResourceManager.GetString("gsPanicStopSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass #.
        /// </summary>
        public static string gsPass {
            get {
                return ResourceManager.GetString("gsPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passes.
        /// </summary>
        public static string gsPasses {
            get {
                return ResourceManager.GetString("gsPasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past End Of Curve.
        /// </summary>
        public static string gsPastEndOfCurve {
            get {
                return ResourceManager.GetString("gsPastEndOfCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string gsPause {
            get {
                return ResourceManager.GetString("gsPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter ABLine.
        /// </summary>
        public static string gsPleaseEnterABLine {
            get {
                return ResourceManager.GetString("gsPleaseEnterABLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure (bar).
        /// </summary>
        public static string gsPressureSensorValueLabel {
            get {
                return ResourceManager.GetString("gsPressureSensorValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure Turn Sensor.
        /// </summary>
        public static string gsPressureTurnSensor {
            get {
                return ResourceManager.GetString("gsPressureTurnSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem Making Path.
        /// </summary>
        public static string gsProblemMakingPath {
            get {
                return ResourceManager.GetString("gsProblemMakingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Will Exit Please Restart.
        /// </summary>
        public static string gsProgramWillExitPleaseRestart {
            get {
                return ResourceManager.GetString("gsProgramWillExitPleaseRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string gsProgress {
            get {
                return ResourceManager.GetString("gsProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proportional Gain.
        /// </summary>
        public static string gsProportionalGain {
            get {
                return ResourceManager.GetString("gsProportionalGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PWM Maximum.
        /// </summary>
        public static string gsPWMMaximum {
            get {
                return ResourceManager.GetString("gsPWMMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PWM Minimum Movement.
        /// </summary>
        public static string gsPWMMinimumMov {
            get {
                return ResourceManager.GetString("gsPWMMinimumMov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really Reset Everything.
        /// </summary>
        public static string gsReallyResetEverything {
            get {
                return ResourceManager.GetString("gsReallyResetEverything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        public static string gsRecord {
            get {
                return ResourceManager.GetString("gsRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorded Path File Corrupt.
        /// </summary>
        public static string gsRecordedPathFileIsCorrupt {
            get {
                return ResourceManager.GetString("gsRecordedPathFileIsCorrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorded Path.
        /// </summary>
        public static string gsRecordedPathMenu {
            get {
                return ResourceManager.GetString("gsRecordedPathMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Offset.
        /// </summary>
        public static string gsRemoveOffset {
            get {
                return ResourceManager.GetString("gsRemoveOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string gsReset {
            get {
                return ResourceManager.GetString("gsReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset All.
        /// </summary>
        public static string gsResetAll {
            get {
                return ResourceManager.GetString("gsResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset All For Sure?.
        /// </summary>
        public static string gsResetAllForSure {
            get {
                return ResourceManager.GetString("gsResetAllForSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset To 100%.
        /// </summary>
        public static string gsResetTo100 {
            get {
                return ResourceManager.GetString("gsResetTo100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Wizard.
        /// </summary>
        public static string gsRestartWiz {
            get {
                return ResourceManager.GetString("gsRestartWiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string gsResume {
            get {
                return ResourceManager.GetString("gsResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string gsRight {
            get {
                return ResourceManager.GetString("gsRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll.
        /// </summary>
        public static string gsRoll {
            get {
                return ResourceManager.GetString("gsRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll Check.
        /// </summary>
        public static string gsRollChack {
            get {
                return ResourceManager.GetString("gsRollChack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll Correction Graph.
        /// </summary>
        public static string gsRollCorrectionGraph {
            get {
                return ResourceManager.GetString("gsRollCorrectionGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll Degrees.
        /// </summary>
        public static string gsRollDegrees {
            get {
                return ResourceManager.GetString("gsRollDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll Function.
        /// </summary>
        public static string gsRollFunction {
            get {
                return ResourceManager.GetString("gsRollFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Park on level surface and touch &quot;Zero Roll&quot;.
        /// </summary>
        public static string gsRollNote {
            get {
                return ResourceManager.GetString("gsRollNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put vehicle leaning strongly to the right. Roll to the right must be POSITIVE..
        /// </summary>
        public static string gsRollNote1 {
            get {
                return ResourceManager.GetString("gsRollNote1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If not Select Invert Roll.
        /// </summary>
        public static string gsRollNote2 {
            get {
                return ResourceManager.GetString("gsRollNote2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll Zero.
        /// </summary>
        public static string gsRollZero {
            get {
                return ResourceManager.GetString("gsRollZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE.
        /// </summary>
        public static string gsS_East {
            get {
                return ResourceManager.GetString("gsS_East", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SW.
        /// </summary>
        public static string gsS_West {
            get {
                return ResourceManager.GetString("gsS_West", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Return.
        /// </summary>
        public static string gsSaveAndReturn {
            get {
                return ResourceManager.GetString("gsSaveAndReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string gsSaveAs {
            get {
                return ResourceManager.GetString("gsSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Colors.
        /// </summary>
        public static string gsSectionColors {
            get {
                return ResourceManager.GetString("gsSectionColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent To Machine Module.
        /// </summary>
        public static string gsSentToMachineModule {
            get {
                return ResourceManager.GetString("gsSentToMachineModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string gsSet {
            get {
                return ResourceManager.GetString("gsSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Distance Antenna Is From Pivot Axle.
        /// </summary>
        public static string gsSetAntennaDistance {
            get {
                return ResourceManager.GetString("gsSetAntennaDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Antenna Height.
        /// </summary>
        public static string gsSetAntennaHeight {
            get {
                return ResourceManager.GetString("gsSetAntennaHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Antenna Offset.
        /// </summary>
        public static string gsSetAntennaOffset {
            get {
                return ResourceManager.GetString("gsSetAntennaOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Panic Stop Speed.
        /// </summary>
        public static string gsSetPanicStopSpeed {
            get {
                return ResourceManager.GetString("gsSetPanicStopSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetPoint.
        /// </summary>
        public static string gsSetPoint {
            get {
                return ResourceManager.GetString("gsSetPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Track Width.
        /// </summary>
        public static string gsSetTrackWidth {
            get {
                return ResourceManager.GetString("gsSetTrackWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Wheelbase.
        /// </summary>
        public static string gsSetWheelbase {
            get {
                return ResourceManager.GetString("gsSetWheelbase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift GPS Position (cm).
        /// </summary>
        public static string gsShiftGPSPosition {
            get {
                return ResourceManager.GetString("gsShiftGPSPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Introduction.
        /// </summary>
        public static string gsShortIntro {
            get {
                return ResourceManager.GetString("gsShortIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulator On.
        /// </summary>
        public static string gsSimulatorOn {
            get {
                return ResourceManager.GetString("gsSimulatorOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        public static string gsSingle {
            get {
                return ResourceManager.GetString("gsSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * SKIP *  Counts Per Degree and Ackermann Setting?.
        /// </summary>
        public static string gsSkipCPD {
            get {
                return ResourceManager.GetString("gsSkipCPD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow Down Below.
        /// </summary>
        public static string gsSlowDownBelow {
            get {
                return ResourceManager.GetString("gsSlowDownBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smooth AB Curve.
        /// </summary>
        public static string gsSmoothABCurve {
            get {
                return ResourceManager.GetString("gsSmoothABCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string gsSort {
            get {
                return ResourceManager.GetString("gsSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South.
        /// </summary>
        public static string gsSouth {
            get {
                return ResourceManager.GetString("gsSouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacing (cm).
        /// </summary>
        public static string gsSpacing {
            get {
                return ResourceManager.GetString("gsSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Angle.
        /// </summary>
        public static string gsStartAngle {
            get {
                return ResourceManager.GetString("gsStartAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start or Delete A Boundary.
        /// </summary>
        public static string gsStartDeleteABoundary {
            get {
                return ResourceManager.GetString("gsStartDeleteABoundary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start New Field.
        /// </summary>
        public static string gsStartNewField {
            get {
                return ResourceManager.GetString("gsStartNewField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Wizard.
        /// </summary>
        public static string gsStartWiz {
            get {
                return ResourceManager.GetString("gsStartWiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steer Angle.
        /// </summary>
        public static string gsSteerAngle {
            get {
                return ResourceManager.GetString("gsSteerAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steer Charts.
        /// </summary>
        public static string gsSteerChart {
            get {
                return ResourceManager.GetString("gsSteerChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steer Enable Mode.
        /// </summary>
        public static string gsSteerEnableMode {
            get {
                return ResourceManager.GetString("gsSteerEnableMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button - Push Release, On.   
        ///               Push Release, Off
        ///
        ///Switch - While Pushed is On. 
        ///               Released is Off..
        /// </summary>
        public static string gsSteerInfo {
            get {
                return ResourceManager.GetString("gsSteerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steer Motor Direction.
        /// </summary>
        public static string gsSteerMotorDir {
            get {
                return ResourceManager.GetString("gsSteerMotorDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive slowly and enable Auto Steer. Invert Direction if steer motor turns the wrong way.
        ///Test with Arrows..
        /// </summary>
        public static string gsSteerMotorDirNote {
            get {
                return ResourceManager.GetString("gsSteerMotorDirNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steer Switch.
        /// </summary>
        public static string gsSteerSwitch {
            get {
                return ResourceManager.GetString("gsSteerSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steer Wizard.
        /// </summary>
        public static string gsSteerWizard {
            get {
                return ResourceManager.GetString("gsSteerWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now go drive an AB Line and fine tune settings based on your speed and soil conditions.
        ///
        ///Remember: CPD, Min PWM, and Look Ahead are critical settings..
        /// </summary>
        public static string gsSteerWizFinishNote {
            get {
                return ResourceManager.GetString("gsSteerWizFinishNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Record Pause Boundary.
        /// </summary>
        public static string gsStopRecordPauseBoundary {
            get {
                return ResourceManager.GetString("gsStopRecordPauseBoundary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch.
        /// </summary>
        public static string gsSwitch {
            get {
                return ResourceManager.GetString("gsSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Log Viewer.
        /// </summary>
        public static string gsSystemLogViewer {
            get {
                return ResourceManager.GetString("gsSystemLogViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions.
        /// </summary>
        public static string gsTermsAndConditions {
            get {
                return ResourceManager.GetString("gsTermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AgOpenGPS is protected under the GPLv3 License.
        /// </summary>
        public static string gsTermsParagraph1 {
            get {
                return ResourceManager.GetString("gsTermsParagraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you distribute copies of this FREE program, whether gratis or for a fee, improved, changed, you must pass on to the recipients the same freedoms that you received as Outlined in the GPLv3 License..
        /// </summary>
        public static string gsTermsParagraph2 {
            get {
                return ResourceManager.GetString("gsTermsParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must make sure that they, too, receive or can get the source code.  And you must show them these terms so they know their rights. Don&apos;t steal others work and call it your own..
        /// </summary>
        public static string gsTermsParagraph3 {
            get {
                return ResourceManager.GetString("gsTermsParagraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AgOpenGPS is strictly educational software for learning about guidance systems, GPS messaging and theoretical machine control applications.
        ///
        ///It should not be used on real equipment under any circumstances. A simulator is provided for the student to safely experience machine guidance.
        ///
        ///The software does not include any safety systems and none are implied.
        ///
        ///Use at your own risk..
        /// </summary>
        public static string gsTermsParagraph4 {
            get {
                return ResourceManager.GetString("gsTermsParagraph4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Thx to Contributors:.
        /// </summary>
        public static string gsThanks {
            get {
                return ResourceManager.GetString("gsThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To File.
        /// </summary>
        public static string gsToFile {
            get {
                return ResourceManager.GetString("gsToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too Fast.
        /// </summary>
        public static string gsTooFast {
            get {
                return ResourceManager.GetString("gsTooFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Field View.
        /// </summary>
        public static string gsTopFieldView {
            get {
                return ResourceManager.GetString("gsTopFieldView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tram Lines.
        /// </summary>
        public static string gsTramLines {
            get {
                return ResourceManager.GetString("gsTramLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn AB Curve On.
        /// </summary>
        public static string gsTurnABCurveOn {
            get {
                return ResourceManager.GetString("gsTurnABCurveOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn On Contour of Make AB Line.
        /// </summary>
        public static string gsTurnOnContourOrMakeABLine {
            get {
                return ResourceManager.GetString("gsTurnOnContourOrMakeABLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Sensor.
        /// </summary>
        public static string gsTurnSensor {
            get {
                return ResourceManager.GetString("gsTurnSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Selected.
        /// </summary>
        public static string gsUseSelected {
            get {
                return ResourceManager.GetString("gsUseSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Settings.
        /// </summary>
        public static string gsViewAllSettings {
            get {
                return ResourceManager.GetString("gsViewAllSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAS Calibration.
        /// </summary>
        public static string gsWASCalibration {
            get {
                return ResourceManager.GetString("gsWASCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAS Zeroing.
        /// </summary>
        public static string gsWASZeroing {
            get {
                return ResourceManager.GetString("gsWASZeroing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive straight forward and Touch Zero.
        /// </summary>
        public static string gsWASZeroNote {
            get {
                return ResourceManager.GetString("gsWASZeroNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebCam.
        /// </summary>
        public static string gsWebCam {
            get {
                return ResourceManager.GetString("gsWebCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West.
        /// </summary>
        public static string gsWest {
            get {
                return ResourceManager.GetString("gsWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Still Open.
        /// </summary>
        public static string gsWindowsStillOpen {
            get {
                return ResourceManager.GetString("gsWindowsStillOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizards.
        /// </summary>
        public static string gsWizards {
            get {
                return ResourceManager.GetString("gsWizards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XTE Chart.
        /// </summary>
        public static string gsXTEChart {
            get {
                return ResourceManager.GetString("gsXTEChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero.
        /// </summary>
        public static string gsZero {
            get {
                return ResourceManager.GetString("gsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 = Off.
        /// </summary>
        public static string gsZeroEqualsOff {
            get {
                return ResourceManager.GetString("gsZeroEqualsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero or +5.
        /// </summary>
        public static string gsZeroOrPlusFive {
            get {
                return ResourceManager.GetString("gsZeroOrPlusFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero Roll.
        /// </summary>
        public static string gsZeroRoll {
            get {
                return ResourceManager.GetString("gsZeroRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.youtube.com/watch?v=iN2cZ8avHag.
        /// </summary>
        public static string v_AboutIntro {
            get {
                return ResourceManager.GetString("v_AboutIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.youtube.com/watch?v=fE3TPRIRSFg.
        /// </summary>
        public static string v_RecordedPathForm {
            get {
                return ResourceManager.GetString("v_RecordedPathForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.youtube.com/watch?v=3SdvYgx8HHc.
        /// </summary>
        public static string v_SteerSettingsForm {
            get {
                return ResourceManager.GetString("v_SteerSettingsForm", resourceCulture);
            }
        }
    }
}
